export const ARTTHEME_TYPES = [
    "love",
    "war",
    "death",
    "nature",
    "beauty",
    "aging",
    "desire",
    "dreams",
    "coming of age",
    "destiny",
    "depression",
    "courage",
    "spirituality",
    "happiness",
    "god",
    "friendship",
    "heartbreak",
    "imagination",
    "loss / tragedy",
    "memories",
    "mortality",
    "immortality",
    "marriage",
    "rebirth",
    "seasons",
    "sexuality",
    "religion",
    "secrets",
    "man and nature",
    "peace",
    "pain",
    "isolation",
    "eternity",
    "earth",
    "emotions",
    "faith",
    "fear",
    "grief",
    "forgiveness",
    "hatred",
    "afterlife",
    "myth",
    "art",
    "anxiety",
    "defeat",
    "heaven",
    "suffering",
    "joy",
    "life",
    "disappointment",
    "stars",
    "trust",
    "gender",
    "history",
    "identity",
    "purpose",
    "regret",
    "encouraging",
    "opportunity",
    "music",
    "roses",
    "innocence",
    "moon",
    "mountains",
    "jealousy",
    "duty and responsibility",
    "supernatural",
    "circle of life",
    "man and masculinity",
    "sunshine",
    "change",
    "flowers"
] as const;

export type ARTTHEME_TYPE = typeof ARTTHEME_TYPES[number];
