import "reflect-metadata";

import Head from "next/head";
import Image from "next/image";

import { GenerateArtCommand } from "../common/commands/generateArt.command";
import { mediator } from "../common/mediatr.config";
import Main from "../components/Main";
import styles from "../styles/Home.module.css";

import type { GetServerSideProps, NextPage } from "next";
export async function getServerSideProps(context: GetServerSideProps) {
    const { name, description } = await mediator.send(new GenerateArtCommand());

    return {
        props: {
            name,
            description
        }
    };
}

const Home: NextPage = (props: any) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>GeoArts NFTs</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Main {...props} />
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
