import "reflect-metadata";

import Head from "next/head";

import { GenerateArtCommand } from "../common/commands/generateArt.command";
import { Art } from "../common/interfaces/art.interface";
import { mediator } from "../common/mediatr.config";
import Main from "../components/Main";
import styles from "../styles/Home.module.css";

import type { GetServerSideProps, NextPage } from "next";
export async function getServerSideProps(context: GetServerSideProps) {
    const art: Art = await mediator.send(new GenerateArtCommand("testing", "testing", "testing"));

    return {
        props: {
            art: JSON.stringify(art)
        }
    };
}

const Home: NextPage = (props: any) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>GeoArt NFTs</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Main {...props} />
            </main>
        </div>
    );
};

export default Home;
